instrumentation:
  root: src
  extensions:
    - .jsx
    - .js
  include-all-sources: true
  default-excludes: true
  excludes: ['constants/*', 'store/*', 'index.js', 'routes.js', 'components/tools/*']
