instrumentation:
  root: src
  extensions:
    - .jsx
    - .js
  include-all-sources: true
  default-excludes: true
  excludes: ['/src/migrations/*', '*createDBs.js', '/src/graphql/*', '*graphql/schema.js', 'index.js']
